Repository webgpu-native/webgpu-headers, pull requests merged in 2025-05, with the labels that each got.

#528 [breaking] Add message argument to QueueWorkDoneCallback
  webgpu.h
  webgpu.yml
Labels: post-RC breaking change

#533 [breaking] Refactor Instance capabilities into features/limits, add SPIRV feature
  doc/articles/Asynchronous Operations.md
  doc/articles/Extensions.md
  tests/compile/main.inl
  webgpu.h
  webgpu.yml
Labels: extensibility, post-RC breaking change

#532 [technically breaking] Auto-destroy Device when the last ref is dropped
  doc/articles/Ownership.md
  webgpu.h
  webgpu.yml
Labels: !discuss, post-RC breaking change

#538 Document the buffer usage enum
  webgpu.h
  webgpu.yml
Labels: buffer mapping, non-breaking

#529 [breaking] Add immediateSize and maxImmediateSize
  webgpu.h
  webgpu.yml
Labels: blocked on w3c, post-RC breaking change

#530 [breaking] Add binding arrays to WGPUBindGroupLayoutEntry
  webgpu.h
  webgpu.yml
Labels: blocked on w3c, post-RC breaking change
